### ISSUE TITLE
Is it available as a bioc package?

### ISSUE THREAD

**Issue by crazyhottommy** [lawremi/HelloRanges#1]
What's the best way to use it? I can do git clone it and source the functions.

Thanks,
Tommy

**Comment by lawremi** [comment]
It has been submitted to Bioconductor and will likely be available in the next release (October). Probably best to wait until then. It's also possible to install GitHub packages with BiocInstaller but I wouldn't recommend it.

**Comment by crazyhottommy** [comment]
thanks!
